const testUserController=()=>{
    try {
        
    } catch (error) {
        console.log("Some error occured",error);
    }
};

module.exports={testUserController}

